apiVersion: apps/v1
kind: Deployment
metadata:
  name: aspnetcore-deployment-BUILDNUMBER
  labels:
    app: aspnetcore
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: aspnetcore
  template:
    metadata:
      labels:
        app: aspnetcore
        version: "BUILDNUMBER"
    spec:
      containers:
        - name: aspnetcore
          image: carloosx/aspnethelloworld
          ports:
            - containerPort: 5000