kind: Service
apiVersion: v1
metadata:
  name: aspnetcore-service-BUILDNUMBER
spec:
  selector:
    app: aspnetcore
  ports:
    - protocol: "TCP"
      # Port accessible inside cluster
      port: 5000
      # Port to forward to inside the pod
      targetPort: 5000
  type: LoadBalancer
  externalIPs:
    - 192.168.99.100